// SHOPPING CART
export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const FETCH_CART_ITEMS_FAIL = "FETCH_CART_ITEMS_FAIL";

export const UPDATE_CART_ITEMS = "UPDATE_CART_ITEMS";
export const UPDATE_CART_LOADING = "UPDATE_CART_LOADING";
export const UPDATE_CART_ITEMS_FAIL = "UPDATE_CART_ITEMS_FAIL";


// DELIVERY
export const FETCH_DELIVERY_AND_CONTACT_DATA = "FETCH_DELIVERY_AND_CONTACT_DATA";
export const STORE_DELIVERY_AND_CONTACT_DATA = "STORE_DELIVERY_AND_CONTACT_DATA";
